safe_bayesian_optimization_node:
  ros__parameters:
    opt: 
      threshold: 0
      beta: 2.0
      lipshitz: 1.0
      f_min: 0.0
      
    # Terrain map request parameters
    terrain_map:
      width: 2.0
      height: 2.0
      width_cells: 20
      height_cells: 20
      
    # Node configuration
    node:
      update_rate: 10.0  # Hz
      log_level: "info"
      enable_visualization: true
