safe_bayesian_optimization_node:
  ros__parameters:
    opt: 
      beta: 2.0
      lipshitz: 1.0
      f_min: 300.0
      
    # Terrain map request parameters
    terrain_map:
      width: 300.0
      height: 300.0
      width_cells: 300
      height_cells: 300
      
    # Reactive planner diffeomorphism parameters
    reactive_planner:
      p: 2.0                    # R-function exponent
      epsilon: 0.1              # Distance for the switches
      varepsilon: 0.05          # Distance allowed to dilate the polygon
      mu_1: 1.0                 # Switch exponent mu1
      mu_2: 1.0                 # Switch exponent mu2
      robot_radius: 0.3         # Robot radius for collision avoidance (meters)
      
    # Debug configuration
    debug:
      publish_debug_image: false
      
    # Node configuration
    node:
      update_rate: 10.0  # Hz
      log_level: "info"
      enable_visualization: true
